//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdLabel.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VdLabel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全デスクトップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllDesktops {
            get {
                return ResourceManager.GetString("AllDesktops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでにVdLabelが起動中です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC起動時に自動起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoStartOnBoot {
            get {
                return ResourceManager.GetString("AutoStartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoStartup {
            get {
                return ResourceManager.GetString("AutoStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を自動起動に登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoStartupRegistered {
            get {
                return ResourceManager.GetString("AutoStartupRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の自動起動を解除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoStartupUnregistered {
            get {
                return ResourceManager.GetString("AutoStartupUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョンのチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckNewVersion {
            get {
                return ResourceManager.GetString("CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新内容の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckReleaseNotes {
            get {
                return ResourceManager.GetString("CheckReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandInterval {
            get {
                return ResourceManager.GetString("CommandInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandSuccess {
            get {
                return ResourceManager.GetString("CommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DesktopList {
            get {
                return ResourceManager.GetString("DesktopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DesktopSettings {
            get {
                return ResourceManager.GetString("DesktopSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayDuration {
            get {
                return ResourceManager.GetString("DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayPosition {
            get {
                return ResourceManager.GetString("DisplayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplaySize {
            get {
                return ResourceManager.GetString("DisplaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全般設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image files (*.bmp;*.jpg;*.jpeg;*.png)|*.bmp;*.jpg;*.jpeg;*.png|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像パス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョン: {0} のインストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallNewVersion {
            get {
                return ResourceManager.GetString("InstallNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新版をインストールしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallUpdatePrompt {
            get {
                return ResourceManager.GetString("InstallUpdatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameCommand {
            get {
                return ResourceManager.GetString("NameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドの出力結果を名前に反映させます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameCommandTooltip {
            get {
                return ResourceManager.GetString("NameCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前表示位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameDisplayPosition {
            get {
                return ResourceManager.GetString("NameDisplayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のWindowsバージョンでは仮想デスクトップの名前同期はサポートされません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NameSyncNotSupported {
            get {
                return ResourceManager.GetString("NameSyncNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョン: {0} がリリースされました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョン {0} がリリースされました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewVersionReleased {
            get {
                return ResourceManager.GetString("NewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドの結果をUTF-8として受け取る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReceiveCommandAsUtf8 {
            get {
                return ResourceManager.GetString("ReceiveCommandAsUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップ一覧の更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshDesktopList {
            get {
                return ResourceManager.GetString("RefreshDesktopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像が設定されているときに名前を表示するかどうか に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowNameWhenImageSet {
            get {
                return ResourceManager.GetString("ShowNameWhenImageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このバージョンはスキップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkipThisVersion {
            get {
                return ResourceManager.GetString("SkipThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り替え通知画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SwitchNotificationImage {
            get {
                return ResourceManager.GetString("SwitchNotificationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ウィンドウ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetWindow {
            get {
                return ResourceManager.GetString("TargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
