//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdLabel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VdLabel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全デスクトップ.
        /// </summary>
        internal static string AllDesktops {
            get {
                return ResourceManager.GetString("AllDesktops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動起動.
        /// </summary>
        internal static string AutoStartup {
            get {
                return ResourceManager.GetString("AutoStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を自動起動に登録しました。.
        /// </summary>
        internal static string AutoStartupRegistered {
            get {
                return ResourceManager.GetString("AutoStartupRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の自動起動を解除しました。.
        /// </summary>
        internal static string AutoStartupUnregistered {
            get {
                return ResourceManager.GetString("AutoStartupUnregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC起動時に自動起動.
        /// </summary>
        internal static string AutoStartOnBoot {
            get {
                return ResourceManager.GetString("AutoStartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいバージョンのチェック.
        /// </summary>
        internal static string CheckNewVersion {
            get {
                return ResourceManager.GetString("CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新内容の確認.
        /// </summary>
        internal static string CheckReleaseNotes {
            get {
                return ResourceManager.GetString("CheckReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンド失敗.
        /// </summary>
        internal static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンド間隔.
        /// </summary>
        internal static string CommandInterval {
            get {
                return ResourceManager.GetString("CommandInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンド成功.
        /// </summary>
        internal static string CommandSuccess {
            get {
                return ResourceManager.GetString("CommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop {0}.
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デスクトップ一覧.
        /// </summary>
        internal static string DesktopList {
            get {
                return ResourceManager.GetString("DesktopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デスクトップ設定.
        /// </summary>
        internal static string DesktopSettings {
            get {
                return ResourceManager.GetString("DesktopSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示時間.
        /// </summary>
        internal static string DisplayDuration {
            get {
                return ResourceManager.GetString("DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示位置.
        /// </summary>
        internal static string DisplayPosition {
            get {
                return ResourceManager.GetString("DisplayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示サイズ.
        /// </summary>
        internal static string DisplaySize {
            get {
                return ResourceManager.GetString("DisplaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォントサイズ.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全般設定.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.bmp;*.jpg;*.jpeg;*.png)|*.bmp;*.jpg;*.jpeg;*.png|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像パス.
        /// </summary>
        internal static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいバージョン: {0} のインストール.
        /// </summary>
        internal static string InstallNewVersion {
            get {
                return ResourceManager.GetString("InstallNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前コマンド.
        /// </summary>
        internal static string NameCommand {
            get {
                return ResourceManager.GetString("NameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドの出力結果を名前に反映させます.
        /// </summary>
        internal static string NameCommandTooltip {
            get {
                return ResourceManager.GetString("NameCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前表示位置.
        /// </summary>
        internal static string NameDisplayPosition {
            get {
                return ResourceManager.GetString("NameDisplayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のWindowsバージョンでは仮想デスクトップの名前同期はサポートされません.
        /// </summary>
        internal static string NameSyncNotSupported {
            get {
                return ResourceManager.GetString("NameSyncNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいバージョン: {0} がリリースされました.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドの結果をUTF-8として受け取る.
        /// </summary>
        internal static string ReceiveCommandAsUtf8 {
            get {
                return ResourceManager.GetString("ReceiveCommandAsUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デスクトップ一覧の更新.
        /// </summary>
        internal static string RefreshDesktopList {
            get {
                return ResourceManager.GetString("RefreshDesktopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像が設定されているときに名前を表示するかどうか.
        /// </summary>
        internal static string ShowNameWhenImageSet {
            get {
                return ResourceManager.GetString("ShowNameWhenImageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り替え通知画像.
        /// </summary>
        internal static string SwitchNotificationImage {
            get {
                return ResourceManager.GetString("SwitchNotificationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象ウィンドウ.
        /// </summary>
        internal static string TargetWindow {
            get {
                return ResourceManager.GetString("TargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テスト.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字色.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
